
[functions.add-language]
enabled = true
verify_jwt = false
import_map = "./functions/add-language/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/add-language/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/add-language/*.html" ]

[functions.process-reflection]
enabled = true
verify_jwt = false
import_map = "./functions/process-reflection/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-reflection/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-reflection/*.html" ]

[functions.interpret]
enabled = true
verify_jwt = false
import_map = "./functions/interpret/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/interpret/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/interpret/*.html" ]

[functions.add-behaviours-language]
enabled = true
verify_jwt = false
import_map = "./functions/add-behaviours-language/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/add-behaviours-language/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/add-behaviours-language/*.html" ]

[functions.add-pattern-chakra-language]
enabled = true
verify_jwt = false
import_map = "./functions/add-pattern-chakra-language/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/add-pattern-chakra-language/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/add-pattern-chakra-language/*.html" ]

[functions.add-oracle-cards-language]
enabled = true
verify_jwt = false
import_map = "./functions/add-oracle-cards-language/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/add-oracle-cards-language/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/add-oracle-cards-language/*.html" ]

[functions.vision]
enabled = true
verify_jwt = false
import_map = "./functions/vision/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/vision/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/vision/*.html" ]

[functions.transcribe]
enabled = true
verify_jwt = false
import_map = "./functions/transcribe/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/transcribe/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/transcribe/*.html" ]

[functions.generate-ai-response]
enabled = true
verify_jwt = false
import_map = "./functions/generate-ai-response/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-ai-response/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-ai-response/*.html" ]

[functions.translate-emotionally]
enabled = true
verify_jwt = false
import_map = "./functions/translate-emotionally/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/translate-emotionally/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/translate-emotionally/*.html" ]
